interface RedditComment {
	archived: boolean,
	author: string,
	author_cakeday?: boolean, // 316646/100109100 (0.32%)
	author_flair_css_class: null|string,
	author_flair_template_id: null|string,
	author_flair_text: null|string,
	body: string,
	can_gild: boolean,
	can_mod_post: boolean,
	controversiality: number,
	created_utc: number,
	distinguished: null|"moderator"|"admin"|"special",
	edited: boolean|number,
	gilded: number,
	id: string,
	is_submitter: boolean,
	link_id: string,
	no_follow: boolean,
	parent_id: string,
	permalink: string,
	removal_reason: null|"legal",
	retrieved_on: number,
	score: number,
	score_hidden: boolean,
	send_replies: boolean,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	subreddit_type: "public"|"restricted"|"user"|"gold_restricted",
}