interface RedditPost_2007 {
	approved?: boolean,
	archived: boolean,
	author: string,
	author_cakeday?: boolean,
	author_flair_background_color: null|"",
	author_flair_css_class: null|string,
	author_flair_richtext?: {
		e: "text",
		t: string,
	}[],
	author_flair_text: null|string,
	author_flair_text_color: null|"dark",
	author_flair_type?: "text"|"richtext",
	brand_safe: boolean,
	can_gild: boolean,
	contest_mode: boolean,
	created_utc: number,
	distinguished: null,
	domain: string,
	edited: boolean,
	gilded: number,
	hidden: boolean,
	hide_score: boolean,
	id: string,
	ignore_reports?: boolean,
	is_crosspostable: boolean,
	is_reddit_media_domain: boolean,
	is_self: boolean,
	is_video: boolean,
	link_flair_background_color?: "",
	link_flair_css_class: null|"nonwhitelistedchannel"|"env",
	link_flair_richtext: {
		e: "text",
		t: "Non-whitelisted Youtube Channel"|"Environment"|"Unacceptable Title",
	}[],
	link_flair_text: null|"Non-whitelisted Youtube Channel"|"Environment"|"Unacceptable Title",
	link_flair_text_color: "dark",
	link_flair_type: "text"|"richtext",
	locked: boolean,
	media: null|{
		oembed: {
			author_name?: "chrisofduke"|"sevim1987"|"Josh McAdams"|"Chase Nunes"|"Google"|"HardwareWars"|"CanadiansNanaimo"|"Sidewinder77"|"J"|"chatni02"|"MadGangster"|"dayjoborchestra",
			author_url?: string,
			description?: string,
			height: number,
			html: string,
			provider_name: "YouTube"|"Google Maps",
			provider_url: "https://www.youtube.com/"|"http://youtube.com"|"http://www.youtube.com/"|"http://google.com/maps",
			thumbnail_height: number,
			thumbnail_url: string,
			thumbnail_width: number,
			title?: string,
			type: "video"|"rich",
			url?: string,
			version: "1.0",
			width: number,
		},
		type: "youtube.com"|"maps.google.com"|"br.youtube.com",
	},
	media_embed: {
		content?: string,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	no_follow: boolean,
	num_comments: number,
	num_crossposts: number,
	over_18: boolean,
	parent_whitelist_status: "all_ads"|"promo_adult_nsfw"|null,
	permalink: string,
	post_hint?: "link"|"rich:video"|"image",
	preview?: {
		enabled: boolean,
		images: {
			id: string,
			resolutions: {
				height: number,
				url: string,
				width: number,
			}[],
			source: {
				height: number,
				url: string,
				width: number,
			},
			variants: {
				gif?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				mp4?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				nsfw?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				obfuscated?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
			},
		}[],
	},
	removed?: boolean,
	retrieved_on: number,
	rte_mode: "markdown",
	score: number,
	secure_media: null|{
		oembed: {
			author_name?: "chrisofduke"|"sevim1987"|"Josh McAdams"|"Chase Nunes"|"Google"|"HardwareWars"|"CanadiansNanaimo"|"Sidewinder77"|"J"|"chatni02"|"MadGangster"|"dayjoborchestra",
			author_url?: string,
			description?: string,
			height: number,
			html: string,
			provider_name: "YouTube"|"Google Maps",
			provider_url: "https://www.youtube.com/"|"http://youtube.com"|"http://www.youtube.com/"|"http://google.com/maps",
			thumbnail_height: number,
			thumbnail_url: string,
			thumbnail_width: number,
			title?: string,
			type: "video"|"rich",
			url?: string,
			version: "1.0",
			width: number,
		},
		type: "youtube.com"|"maps.google.com"|"br.youtube.com",
	},
	secure_media_embed: {
		content?: string,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	selftext: ""|"[deleted]",
	send_replies: boolean,
	spam?: boolean,
	spoiler: boolean,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	subreddit_name_prefixed: string,
	subreddit_type: "archived"|"public"|"restricted",
	suggested_sort: null|"confidence"|"new",
	thumbnail: string,
	thumbnail_height?: null|number,
	thumbnail_width?: null|number,
	title: string,
	url: string,
	whitelist_status: "all_ads"|"promo_adult_nsfw"|null,
}
