interface RedditPost_2008 {
	adserver_click_url?: null,
	adserver_imp_pixel?: null,
	approved?: boolean,
	archived: boolean,
	author: string,
	author_cakeday?: boolean,
	author_flair_background_color: null|""|"#edeff1",
	author_flair_css_class: null|string,
	author_flair_richtext?: {
		a?: ":bastok:",
		e: "text"|"emoji",
		t?: string,
		u?: string,
	}[],
	author_flair_text: null|string,
	author_flair_text_color: null|"dark",
	author_flair_type?: "text"|"richtext",
	author_id?: string|null,
	brand_safe: boolean,
	can_gild: boolean,
	contest_mode: boolean,
	created_utc: number,
	distinguished: null|"moderator",
	domain: string,
	domain_override?: null,
	edited: boolean|number,
	embed_type?: null,
	embed_url?: null,
	events?: [],
	eventsOnRender?: [],
	gilded: number,
	hidden: boolean,
	hide_score: boolean,
	href_url?: string,
	id: string,
	ignore_reports?: boolean,
	is_blank?: boolean,
	is_crosspostable: boolean,
	is_reddit_media_domain: boolean,
	is_self: boolean,
	is_video: boolean,
	link_flair_background_color?: "",
	link_flair_css_class: null|string,
	link_flair_richtext: {
		e: "text",
		t: string,
	}[],
	link_flair_template_id?: "61a5ce90-74a5-11e7-a4de-0e5517db016e"|"b6f7a02a-74a6-11e7-8ebf-0e76a733d78a",
	link_flair_text: null|string,
	link_flair_text_color: "dark",
	link_flair_type: "text"|"richtext",
	locked: boolean,
	media: null|{
		oembed: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			height: number,
			html: string,
			provider_name: "YouTube"|"Google Maps"|"Trailer Addict"|"SlideShare"|"Vimeo"|"Scribd"|"Behance",
			provider_url: "https://www.youtube.com/"|"http://google.com/maps"|"https://www.traileraddict.com"|"http://youtube.com"|"https://www.slideshare.net/"|"https://vimeo.com/"|"https://www.scribd.com/"|"http://www.behance.net",
			thumbnail_height: number,
			thumbnail_url: string,
			thumbnail_width: number,
			title: string,
			type: "video"|"rich",
			url?: string,
			version: "1.0",
			width: number,
		},
		type: "youtube.com"|"uk.youtube.com"|"maps.google.com"|"traileraddict.com"|"slideshare.net"|"vimeo.com"|"au.youtube.com"|"ca.youtube.com"|"scribd.com"|"behance.net",
	},
	media_embed: {
		content?: string,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	mobile_ad_url?: "",
	no_follow: boolean,
	num_comments: number,
	num_crossposts: number,
	original_link?: null,
	outbound_link?: {
		created?: number,
		expiration?: number,
		url?: string,
	},
	over_18: boolean,
	parent_whitelist_status: "all_ads"|"promo_adult_nsfw"|"promo_specified"|"promo_all"|"house_only"|"no_ads"|"promo_adult"|null,
	permalink: string,
	post_hint?: "link"|"image"|"rich:video",
	preview?: {
		enabled: boolean,
		images: {
			id: string,
			resolutions: {
				height: number,
				url: string,
				width: number,
			}[],
			source: {
				height: number,
				url: string,
				width: number,
			},
			variants: {
				gif?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				mp4?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				nsfw?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				obfuscated?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
			},
		}[],
	},
	priority_id?: null,
	promoted?: boolean,
	promoted_by?: null|number,
	promoted_display_name?: null,
	promoted_url?: null,
	removed?: boolean,
	retrieved_on: number,
	rte_mode: "markdown",
	score: number,
	secure_media: null|{
		oembed: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			height: number,
			html: string,
			provider_name: "YouTube"|"Google Maps"|"Trailer Addict"|"SlideShare"|"Vimeo"|"Scribd"|"Behance",
			provider_url: "https://www.youtube.com/"|"http://google.com/maps"|"https://www.traileraddict.com"|"http://youtube.com"|"https://www.slideshare.net/"|"https://vimeo.com/"|"https://www.scribd.com/"|"http://www.behance.net",
			thumbnail_height: number,
			thumbnail_url: string,
			thumbnail_width: number,
			title: string,
			type: "video"|"rich",
			url?: string,
			version: "1.0",
			width: number,
		},
		type: "youtube.com"|"uk.youtube.com"|"maps.google.com"|"traileraddict.com"|"slideshare.net"|"vimeo.com"|"au.youtube.com"|"ca.youtube.com"|"scribd.com"|"behance.net",
	},
	secure_media_embed: {
		content?: string,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	selftext: ""|"[deleted]"|"[removed]",
	send_replies: boolean,
	spam?: boolean,
	spoiler: boolean,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	subreddit_name_prefixed: string,
	subreddit_type: "archived"|"public"|"restricted",
	suggested_sort: null|"confidence"|"new"|"top"|"qa"|"old"|"controversial",
	third_party_trackers?: [],
	third_party_tracking?: null,
	third_party_tracking_2?: null,
	thumbnail: string,
	thumbnail_height?: null|number,
	thumbnail_width?: null|number,
	title: string,
	url: string,
	whitelist_status: "all_ads"|"promo_adult_nsfw"|"promo_specified"|"promo_all"|"house_only"|"no_ads"|"promo_adult"|null,
}
