interface RedditPost_2013 {
	author?: string,
	author_flair_css_class: null|string,
	author_flair_text: null|string,
	banned_by: null|"NorthboundFox",
	created_utc: number,
	distinguished: null|"moderator"|"admin"|"special",
	domain: string,
	downs: number,
	edited: boolean|number,
	gilded: number,
	id: string,
	is_self: boolean,
	link_flair_css_class: null|string,
	link_flair_text: null|string,
	media: null|{
		content?: string,
		height?: number,
		oembed?: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			dominant_colors?: {
				color: number[],
				weight: number,
			}[],
			entropy?: number,
			height: number,
			html: string,
			mean_alpha?: number,
			provider_name: string,
			provider_url: string,
			thumbnail_height?: number,
			thumbnail_url?: string,
			thumbnail_width?: number,
			title?: string,
			type: "video"|"rich",
			url?: string,
			version: "1.0",
			width: number,
		},
		type: string,
		width?: number,
	},
	media_embed: {
		content?: string,
		height?: number,
		scrolling?: boolean,
		width?: number,
	},
	mod_reports: [],
	num_comments: number,
	over_18: boolean,
	permalink: string,
	promoted?: boolean,
	report_reasons: null|[],
	retrieved_on: number,
	score: number,
	secure_media: null|{
		oembed: {
			author_name?: string,
			author_url?: string,
			description?: string,
			height: number,
			html: string,
			mean_alpha?: number,
			provider_name: "YouTube"|"SoundCloud"|"Vimeo"|"SlideShare"|"Wistia, Inc."|"Soundcloud"|"Slideshare",
			provider_url: "http://www.youtube.com/"|"http://soundcloud.com"|"https://vimeo.com/"|"http://youtube.com"|"http://www.slideshare.net"|"http://wistia.com"|"http://vimeo.com",
			thumbnail_height?: number,
			thumbnail_url?: string,
			thumbnail_width?: number,
			title?: string,
			type: "video"|"rich",
			url?: string,
			version: "1.0",
			width: number,
		},
		type: string,
	},
	secure_media_embed: {
		content?: string,
		height?: number,
		scrolling?: boolean,
		width?: number,
	},
	selftext: string,
	selftext_html: null|string,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	thumbnail: string,
	title: string,
	ups: number,
	url: string,
	user_reports: [],
}
