interface RedditPost_2018 {
	adserver_click_url?: null,
	adserver_imp_pixel?: null,
	approved_by?: null,
	archived?: boolean,
	author: string,
	author_cakeday?: boolean,
	author_created_utc?: number|null,
	author_flair_background_color?: null|string,
	author_flair_css_class: null|string,
	author_flair_richtext?: {
		a?: string,
		e: "text"|"emoji",
		t?: string,
		u?: string,
	}[],
	author_flair_template_id?: null|string,
	author_flair_text: null|string,
	author_flair_text_color?: null|"dark"|"light",
	author_flair_type?: "text"|"richtext",
	author_fullname?: string|null,
	author_id?: string|null,
	author_patreon_flair?: boolean,
	banned_by?: null,
	brand_safe?: boolean,
	call_to_action?: "Shop Now"|"Download"|"View More"|"Sign Up"|"Install"|"Watch Now"|"Get Showtimes"|"Get a Quote"|"Play Now"|"Learn More"|"Apply Now"|"Contact Us"|"See Menu"|null,
	can_gild?: boolean,
	can_mod_post?: boolean,
	category?: null|string,
	clicked?: boolean,
	collections?: {
		author_id: string,
		author_name: string,
		collection_id: string,
		created_at_utc: number,
		description?: null|"",
		display_layout?: null,
		last_update_utc: number,
		link_ids: string[],
		permalink?: string,
		subreddit_id: string,
		title: string,
	}[],
	content_categories?: null|("gaming"|"photography"|"entertainment"|"drawing_and_painting"|"videos"|"music"|"diy_and_crafts"|"comics"|"writing")[],
	contest_mode: boolean,
	created?: number,
	created_utc: number,
	crosspost_parent?: string,
	crosspost_parent_list?: {
		approved_at_utc: null,
		approved_by: null,
		archived: boolean,
		author: string,
		author_cakeday?: boolean,
		author_flair_background_color?: null|string,
		author_flair_css_class: null|string,
		author_flair_richtext?: {
			a?: string,
			e: "text"|"emoji",
			t?: string,
			u?: string,
		}[],
		author_flair_template_id?: null|string,
		author_flair_text: null|string,
		author_flair_text_color?: null|"dark"|"light",
		author_flair_type?: "text"|"richtext",
		author_fullname?: string,
		author_patreon_flair?: boolean,
		banned_at_utc: null,
		banned_by: null,
		brand_safe?: boolean,
		can_gild: boolean|null,
		can_mod_post: boolean,
		category?: null|string,
		clicked: boolean,
		collections?: {
			author_id: string,
			author_name: string,
			collection_id: string,
			created_at_utc: number,
			description?: null|"",
			display_layout?: null,
			last_update_utc: number,
			link_ids: string[],
			permalink: string,
			subreddit_id: "t5_kpka5"|"t5_39cf6"|"t5_2t7hh"|"t5_2r61s"|"t5_2r40o"|"t5_2rfxx"|"t5_3oeyf"|"t5_2rjz2"|"t5_2qs08"|"t5_pfqef"|"t5_2cneq",
			title: string,
		}[],
		content_categories?: null|("diy_and_crafts"|"photography"|"gaming"|"drawing_and_painting"|"comics"|"entertainment"|"music"|"videos"|"writing")[],
		contest_mode: boolean,
		created: number,
		created_utc: number,
		distinguished: null|"moderator"|"admin",
		domain: string,
		downs: number,
		edited: boolean|number,
		event_end?: number,
		event_is_live?: boolean,
		event_start?: number,
		gilded: number,
		gildings?: {
			gid_1: number,
			gid_2: number,
			gid_3: number,
		},
		hidden: boolean,
		hide_score: boolean,
		id: string,
		is_crosspostable: boolean,
		is_meta?: boolean,
		is_original_content?: boolean,
		is_reddit_media_domain: boolean,
		is_robot_indexable?: boolean,
		is_self: boolean,
		is_video: boolean,
		likes: null,
		link_flair_background_color?: string,
		link_flair_css_class: null|string,
		link_flair_richtext?: {
			a?: string,
			e: "text"|"emoji",
			t?: string,
			u?: string,
		}[],
		link_flair_template_id?: string|null,
		link_flair_text: null|string,
		link_flair_text_color?: "dark"|"light",
		link_flair_type?: "text"|"richtext",
		locked: boolean,
		media: null|{
			content?: string,
			event_id?: string,
			height?: number,
			oembed?: {
				author_name?: string,
				author_url?: string,
				cache_age?: number,
				description?: string,
				height: number,
				html: string,
				mean_alpha?: number,
				provider_name: string,
				provider_url: string,
				thumbnail_height?: number,
				thumbnail_url?: string,
				thumbnail_width?: number,
				title?: string,
				type: "video"|"rich",
				url?: string,
				version: "1.0",
				width: number,
			},
			reddit_video?: {
				dash_url: string,
				duration: number,
				fallback_url: string,
				height: number,
				hls_url: string,
				is_gif: boolean,
				scrubber_media_url: string,
				transcoding_status: "completed",
				width: number,
			},
			type?: string,
			width?: number,
		},
		media_embed: {
			content?: string,
			height?: number,
			media_domain_url?: string,
			scrolling?: boolean,
			width?: number,
		},
		media_metadata?: null|{
			[key: string]: {
				dashUrl?: string,
				e: "Image"|"RedditVideo"|"AnimatedImage",
				hlsUrl?: string,
				id: string,
				isGif?: boolean,
				m?: "image/jpg"|"image/png"|"image/gif",
				s?: {
					gif?: string,
					mp4?: string,
					u?: string,
					x: number,
					y: number,
				},
				status: "valid",
				x?: number,
				y?: number,
			},
		},
		media_only?: boolean,
		mod_note: null,
		mod_reason_by: null,
		mod_reason_title: null,
		mod_reports: [],
		name: string,
		no_follow?: boolean,
		num_comments: number,
		num_crossposts: number,
		num_reports: null,
		over_18: boolean,
		parent_whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"promo_all"|"no_ads"|"promo_specified"|"promo_adult"|null,
		permalink: string,
		pinned: boolean,
		post_categories?: null,
		post_hint?: "link"|"image"|"rich:video"|"self"|"hosted:video"|"video",
		preview?: {
			enabled: boolean,
			images: {
				id: string,
				resolutions: {
					height: number,
					url: string,
					width: number,
				}[],
				source: {
					height: number,
					url: string,
					width: number,
				},
				variants: {
					gif?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
					mp4?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
					nsfw?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
					obfuscated?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
				},
			}[],
			reddit_video_preview?: {
				dash_url: string,
				duration: number,
				fallback_url: string,
				height: number,
				hls_url: string,
				is_gif: boolean,
				scrubber_media_url: string,
				transcoding_status: "completed",
				width: number,
			},
		},
		previous_visits?: number[],
		pwls?: null|number,
		quarantine: boolean,
		removal_reason: null|"legal",
		report_reasons: null,
		rte_mode?: "markdown"|"richtext",
		saved: boolean,
		score: number,
		secure_media: null|{
			content?: string,
			event_id?: string,
			height?: number,
			oembed?: {
				author_name?: string,
				author_url?: string,
				cache_age?: number,
				description?: string,
				height: number,
				html: string,
				mean_alpha?: number,
				provider_name: string,
				provider_url: string,
				thumbnail_height?: number,
				thumbnail_url?: string,
				thumbnail_width?: number,
				title?: string,
				type: "video"|"rich",
				url?: string,
				version: "1.0",
				width: number,
			},
			reddit_video?: {
				dash_url: string,
				duration: number,
				fallback_url: string,
				height: number,
				hls_url: string,
				is_gif: boolean,
				scrubber_media_url: string,
				transcoding_status: "completed",
				width: number,
			},
			type?: string,
			width?: number,
		},
		secure_media_embed: {
			content?: string,
			height?: number,
			media_domain_url?: string,
			scrolling?: boolean,
			width?: number,
		},
		selftext: string,
		selftext_html: null|string,
		send_replies?: boolean,
		spoiler: boolean,
		stickied: boolean,
		subreddit: string,
		subreddit_id: string,
		subreddit_name_prefixed: string,
		subreddit_subscribers?: number,
		subreddit_type: "public"|"user"|"restricted"|"archived"|"gold_restricted",
		suggested_sort: null|"confidence"|"qa"|"top"|"new"|"old"|"controversial"|"random"|"live",
		thumbnail: string|null,
		thumbnail_height?: number|null,
		thumbnail_width?: number|null,
		title: string,
		ups: number,
		url: string,
		user_reports: [],
		view_count: null,
		visited: boolean,
		whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"promo_all"|"no_ads"|"promo_specified"|"promo_adult"|null,
		wls?: null|number,
	}[],
	distinguished: null|"moderator"|"admin"|"special",
	domain: string,
	domain_override?: null|string,
	downs?: number,
	edited: boolean|number,
	embed_type?: null|"scrape"|"iframe",
	embed_url?: null|string,
	event_end?: number,
	event_is_live?: boolean,
	event_start?: number,
	events?: [],
	eventsOnRender?: [],
	gilded: number,
	gildings?: {
		gid_1: number,
		gid_2: number,
		gid_3: number,
	},
	hidden: boolean,
	hide_score?: boolean,
	href_url?: string,
	id: string,
	is_blank?: boolean,
	is_crosspostable: boolean,
	is_meta?: boolean,
	is_original_content?: boolean,
	is_reddit_media_domain: boolean,
	is_robot_indexable?: boolean,
	is_self: boolean,
	is_video: boolean,
	likes?: null,
	link_flair_background_color?: string,
	link_flair_css_class: null|string,
	link_flair_richtext?: {
		a?: string,
		e: "text"|"emoji",
		t?: string,
		u?: string,
	}[],
	link_flair_template_id?: string|null,
	link_flair_text: null|string,
	link_flair_text_color?: "dark"|"light",
	link_flair_type?: "text"|"richtext",
	locked: boolean,
	media: null|{
		content?: string,
		event_id?: string,
		height?: number,
		oembed?: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			height: number,
			html: string,
			marginheight?: number,
			marginwidth?: number,
			mean_alpha?: number,
			provider_name: string,
			provider_url: string,
			thumbnail_height?: number,
			thumbnail_url?: string,
			thumbnail_width?: number,
			title?: string,
			type: "video"|"rich",
			url?: string,
			version?: "1.0",
			width: number,
		},
		reddit_video?: {
			dash_url: string,
			duration: number,
			fallback_url: string,
			height: number,
			hls_url: string,
			is_gif: boolean,
			scrubber_media_url: string,
			transcoding_status: "completed",
			width: number,
		},
		type?: string,
		width?: number,
	},
	media_embed: {
		content?: string,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	media_metadata?: null|{
		[key: string]: {
			dashUrl?: string,
			e?: "Image"|"AnimatedImage"|"RedditVideo",
			hlsUrl?: string,
			id?: string,
			isGif?: boolean,
			m?: "image/jpg"|"image/png"|"image/gif",
			s?: {
				gif?: string,
				mp4?: string,
				u?: string,
				x: number,
				y: number,
			},
			status: "valid"|"failed",
			x?: number,
			y?: number,
		},
	},
	media_only?: boolean,
	mobile_ad_url?: string,
	mod_reports?: [],
	name?: string,
	no_follow?: boolean,
	num_comments: number,
	num_crossposts: number,
	num_reports?: null,
	original_link?: null|"t3_7p8px9"|"t3_7p8olf"|"t3_7qvdr1",
	outbound_link?: {
	},
	over_18: boolean,
	parent_whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"no_ads"|"promo_all"|"promo_specified"|"promo_adult"|null,
	permalink: string,
	pinned: boolean,
	post_categories?: null,
	post_hint?: "link"|"image"|"rich:video"|"self"|"hosted:video"|"video",
	preview?: {
		enabled: boolean,
		images: {
			id: string,
			resolutions: {
				height: number,
				url: string,
				width: number,
			}[],
			source: {
				height: number,
				url: string,
				width: number,
			},
			variants: {
				gif?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				mp4?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				nsfw?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				obfuscated?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
			},
		}[],
		reddit_video_preview?: {
			dash_url: string,
			duration: number,
			fallback_url: string,
			height: number,
			hls_url: string,
			is_gif: boolean,
			scrubber_media_url: string,
			transcoding_status: "completed",
			width: number,
		},
	},
	previous_visits?: number[],
	priority_id?: null,
	promoted?: boolean,
	promoted_by?: null,
	promoted_display_name?: null|"FX_Official",
	promoted_url?: null|string,
	pwls?: null|number,
	quarantine?: boolean,
	removal_reason?: null|"legal",
	report_reasons?: null,
	retrieved_on: number,
	rte_mode?: "markdown"|"richtext",
	saved?: boolean,
	score: number,
	secure_media: null|{
		content?: string,
		event_id?: string,
		height?: number,
		oembed?: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			height: number,
			html: string,
			marginheight?: number,
			marginwidth?: number,
			mean_alpha?: number,
			provider_name: string,
			provider_url: string,
			thumbnail_height?: number,
			thumbnail_url?: string,
			thumbnail_width?: number,
			title?: string,
			type: "video"|"rich",
			url?: string,
			version?: "1.0",
			width: number,
		},
		reddit_video?: {
			dash_url: string,
			duration: number,
			fallback_url: string,
			height: number,
			hls_url: string,
			is_gif: boolean,
			scrubber_media_url: string,
			transcoding_status: "completed",
			width: number,
		},
		type?: string,
		width?: number,
	},
	secure_media_embed: {
		content?: string,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	selftext: string,
	selftext_html?: string|null,
	send_replies?: boolean,
	show_media?: boolean,
	spoiler: boolean|null,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	subreddit_name_prefixed?: string,
	subreddit_subscribers?: number,
	subreddit_type: "public"|"restricted"|"user"|"private"|"gold_restricted"|"archived",
	suggested_sort: null|"confidence"|"qa"|"new"|"top"|"old"|"controversial"|"random"|"live",
	third_party_trackers?: null|string[],
	third_party_tracking?: null|string,
	third_party_tracking_2?: null,
	thumbnail: string|null,
	thumbnail_height?: number|null,
	thumbnail_width?: number|null,
	title: string,
	ups?: number,
	url: string,
	user_reports?: [],
	visited?: boolean,
	whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"no_ads"|"promo_all"|"promo_specified"|"promo_adult"|null,
	wls?: null|number,
}
