interface RedditPost_2019 {
	adserver_click_url?: null,
	adserver_imp_pixel?: null,
	all_awardings?: {
		award_sub_type?: "GLOBAL"|"COMMUNITY"|"MODERATOR"|"APPRECIATION"|"PREMIUM",
		award_type: "global"|"community"|"moderator",
		coin_price: number,
		coin_reward: number,
		count: number,
		days_of_drip_extension: number,
		days_of_premium: number,
		description: string|null,
		end_date?: null|number,
		giver_coin_reward?: null|number,
		icon_format?: null|"JPG"|"PNG"|"APNG",
		icon_height: number,
		icon_url: string,
		icon_width: number,
		id: string,
		is_enabled: boolean,
		is_new?: boolean,
		name: string,
		penny_donate?: null|number,
		penny_price?: null|number,
		resized_icons: {
			height: number,
			url: string,
			width: number,
		}[],
		start_date?: null|number,
		subreddit_coin_reward?: number,
		subreddit_id: null|string,
	}[],
	allow_live_comments?: boolean,
	archived?: boolean,
	author: string,
	author_cakeday?: boolean,
	author_created_utc?: number|null,
	author_flair_background_color: null|string,
	author_flair_css_class: null|string,
	author_flair_richtext?: {
		a?: string,
		e: "text"|"emoji",
		t?: string,
		u?: string,
	}[],
	author_flair_template_id: null|string,
	author_flair_text: null|string,
	author_flair_text_color: null|"dark"|"light"|"",
	author_flair_type?: "text"|"richtext",
	author_fullname?: string|null,
	author_id?: string|null,
	author_patreon_flair?: boolean,
	author_premium?: boolean,
	awarders?: [],
	call_to_action?: "Learn More"|"Shop Now"|"Sign Up"|"View More"|"Download"|"Watch Now"|"Play Now"|"Apply Now"|"Install"|"Contact Us"|"Get a Quote"|"Get Showtimes"|"See Menu"|""|null,
	can_gild: boolean,
	can_mod_post: boolean,
	category: null|"videos"|"drawing_and_painting"|"gaming"|"photography"|"entertainment"|"writing"|"diy_and_crafts"|"animals"|"music"|"memes"|"food"|"funny"|"",
	collections?: {
		author_id: string,
		author_name: string,
		collection_id: string,
		created_at_utc: number,
		description: string|null,
		display_layout: null|"GALLERY"|"TIMELINE",
		last_update_utc: number,
		link_ids: string[],
		permalink: string,
		sr_detail?: {
			banner_img: string,
			banner_size: number[],
			community_icon: string,
			icon_img: string,
			icon_size: number[],
			key_color: "#7e53c1"|"#46d160",
			mod_permissions: [],
			name: "t5_3oeyf"|"t5_2qs08",
			over_18: boolean,
			primary_color: "#a964db"|"#bbbdbf",
			sr: "FortNiteBR"|"NASCAR",
			sr_display_name_prefixed: "r/FortNiteBR"|"r/NASCAR",
			subreddit_type: "public",
			subscribers: number,
			title: "Fortnite: Battle Royale"|"NASCAR on Reddit: News from the oval",
			url: "/r/FortNiteBR/"|"/r/NASCAR/",
			user_can_crosspost: null|boolean,
			whitelist_status: "all_ads",
		},
		subreddit_id: string,
		title: string,
	}[],
	content_categories: null|("photography"|"drawing_and_painting"|"gaming"|"entertainment"|"videos"|"diy_and_crafts"|"music"|"writing"|"comics")[],
	contest_mode: boolean,
	created_utc: number,
	crosspost_parent?: string,
	crosspost_parent_list?: {
		all_awardings?: {
			award_sub_type?: "GLOBAL"|"COMMUNITY"|"MODERATOR"|"APPRECIATION"|"PREMIUM",
			award_type: "global"|"community"|"moderator",
			coin_price: number,
			coin_reward: number,
			count: number,
			days_of_drip_extension: number,
			days_of_premium: number,
			description: string|null,
			end_date?: null|number,
			giver_coin_reward?: null|number,
			icon_format?: null|"JPG"|"PNG"|"APNG",
			icon_height: number,
			icon_url: string,
			icon_width: number,
			id: string,
			is_enabled: boolean,
			is_new?: boolean,
			name: string,
			penny_donate?: null|number,
			penny_price?: null|number,
			resized_icons: {
				height: number,
				url: string,
				width: number,
			}[],
			start_date?: null|number,
			subreddit_coin_reward?: number,
			subreddit_id: null|string,
		}[],
		allow_live_comments?: boolean,
		approved_at_utc: null,
		approved_by: null,
		archived: boolean,
		author: string,
		author_cakeday?: boolean,
		author_flair_background_color: null|string,
		author_flair_css_class: null|string,
		author_flair_richtext?: {
			a?: string,
			e: "text"|"emoji",
			t?: string,
			u?: string,
		}[],
		author_flair_template_id: null|string,
		author_flair_text: null|string,
		author_flair_text_color: null|"dark"|"light"|"",
		author_flair_type?: "text"|"richtext",
		author_fullname?: string,
		author_patreon_flair?: boolean,
		author_premium?: boolean,
		awarders?: [],
		banned_at_utc: null,
		banned_by: null,
		call_to_action?: "Shop Now"|"Sign Up"|"Learn More"|"Download"|"Install"|"See Menu"|"Play Now"|"View More"|"Watch Now"|"Get Showtimes"|"",
		can_gild: boolean,
		can_mod_post: boolean,
		category: null|"drawing_and_painting"|"photography"|"gaming"|"animals"|"entertainment"|"diy_and_crafts"|"videos"|"music"|"memes"|""|"food"|"funny"|"writing"|"pics_and_gifs"|"art",
		clicked: boolean,
		collections?: {
			author_id: string,
			author_name: string,
			collection_id: string,
			created_at_utc: number,
			description: string|null,
			display_layout: null|"GALLERY"|"TIMELINE",
			last_update_utc: number,
			link_ids: string[],
			permalink: string,
			subreddit_id: string,
			title: string,
		}[],
		content_categories: null|("photography"|"drawing_and_painting"|"gaming"|"comics"|"entertainment"|"diy_and_crafts"|"writing"|"videos"|"music")[],
		contest_mode: boolean,
		created: number,
		created_utc: number,
		discussion_type?: null|"CHAT",
		distinguished: null|"moderator"|"admin",
		domain: string,
		downs: number,
		edited: boolean|number,
		event_end?: number,
		event_is_live?: boolean,
		event_start?: number,
		gilded: number,
		gildings: {
			gid_1?: number,
			gid_2?: number,
			gid_3?: number,
		},
		hidden: boolean,
		hide_score: boolean,
		id: string,
		is_crosspostable: boolean,
		is_meta: boolean,
		is_original_content: boolean,
		is_reddit_media_domain: boolean,
		is_robot_indexable: boolean,
		is_self: boolean,
		is_video: boolean,
		likes: null,
		link_flair_background_color: string,
		link_flair_css_class: null|string,
		link_flair_richtext: {
			a?: string,
			e: "text"|"emoji",
			t?: string,
			u?: string,
		}[],
		link_flair_template_id?: string|null,
		link_flair_text: null|string,
		link_flair_text_color: "dark"|"light",
		link_flair_type: "text"|"richtext",
		locked: boolean,
		media: null|{
			content?: string,
			event_id?: string,
			height?: number,
			oembed?: {
				author_name?: string,
				author_url?: string,
				cache_age?: number,
				description?: string,
				height: number|null,
				html: string,
				mean_alpha?: number,
				provider_name: string,
				provider_url: string,
				thumbnail_height?: number,
				thumbnail_url?: string,
				thumbnail_width?: number,
				title?: string,
				type: "video"|"rich",
				url?: string,
				version: "1.0",
				width: number,
			},
			reddit_video?: {
				dash_url: string,
				duration: number,
				fallback_url: string,
				height: number,
				hls_url: string,
				is_gif: boolean,
				scrubber_media_url: string,
				transcoding_status: "completed",
				width: number,
			},
			type?: string,
			width?: number,
		},
		media_embed: {
			content?: string,
			height?: number,
			scrolling?: boolean,
			width?: number,
		},
		media_metadata?: {
			[key: string]: {
				dashUrl?: string,
				e?: "Image"|"RedditVideo"|"AnimatedImage",
				hlsUrl?: string,
				id?: string,
				isGif?: boolean,
				m?: "image/png"|"image/jpg"|"image/gif",
				p?: {
					u: string,
					x: number,
					y: number,
				}[],
				s?: {
					gif?: string,
					mp4?: string,
					u?: string,
					x: number,
					y: number,
				},
				status: "valid"|"failed"|"unprocessed",
				x?: number,
				y?: number,
			},
		}|null,
		media_only: boolean,
		mod_note: null,
		mod_reason_by: null,
		mod_reason_title: null,
		mod_reports: [],
		name: string,
		no_follow: boolean,
		num_comments: number,
		num_crossposts: number,
		num_reports: null,
		over_18: boolean,
		parent_whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"no_ads"|"promo_all"|"some_ads"|null,
		permalink: string,
		pinned: boolean,
		post_hint?: "image"|"link"|"rich:video"|"hosted:video"|"self"|"video",
		preview?: {
			enabled: boolean,
			images: {
				id: string,
				resolutions: {
					height: number,
					url: string,
					width: number,
				}[],
				source: {
					height: number,
					url: string,
					width: number,
				},
				variants: {
					gif?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
					mp4?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
					nsfw?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
					obfuscated?: {
						resolutions: {
							height: number,
							url: string,
							width: number,
						}[],
						source: {
							height: number,
							url: string,
							width: number,
						},
					},
				},
			}[],
			reddit_video_preview?: {
				dash_url: string,
				duration: number,
				fallback_url: string,
				height: number,
				hls_url: string,
				is_gif: boolean,
				scrubber_media_url: string,
				transcoding_status: "completed",
				width: number,
			},
		},
		previous_visits?: number[],
		pwls: number|null,
		quarantine: boolean,
		removal_reason: null|"legal",
		removed_by?: null,
		removed_by_category?: null|"deleted"|"reddit"|"moderator"|"copyright_takedown"|"author"|"anti_evil_ops"|"content_takedown"|"community_ops"|"automod_filtered",
		report_reasons: null,
		saved: boolean,
		score: number,
		secure_media: null|{
			content?: string,
			event_id?: string,
			height?: number,
			oembed?: {
				author_name?: string,
				author_url?: string,
				cache_age?: number,
				description?: string,
				height: number|null,
				html: string,
				mean_alpha?: number,
				provider_name: string,
				provider_url: string,
				thumbnail_height?: number,
				thumbnail_url?: string,
				thumbnail_width?: number,
				title?: string,
				type: "video"|"rich",
				url?: string,
				version: "1.0",
				width: number,
			},
			reddit_video?: {
				dash_url: string,
				duration: number,
				fallback_url: string,
				height: number,
				hls_url: string,
				is_gif: boolean,
				scrubber_media_url: string,
				transcoding_status: "completed",
				width: number,
			},
			type?: string,
			width?: number,
		},
		secure_media_embed: {
			content?: string,
			height?: number,
			media_domain_url?: string,
			scrolling?: boolean,
			width?: number,
		},
		selftext: string,
		selftext_html: null|string,
		send_replies: boolean,
		spoiler: boolean,
		steward_reports?: [],
		stickied: boolean,
		subreddit: string,
		subreddit_id: string,
		subreddit_name_prefixed: string,
		subreddit_subscribers: number,
		subreddit_type: "public"|"user"|"restricted"|"archived"|"gold_restricted",
		suggested_sort: null|"confidence"|"top"|"qa"|"new"|"controversial"|"old"|"random"|"live",
		thumbnail: string,
		thumbnail_height?: number|null,
		thumbnail_width?: number|null,
		title: string,
		total_awards_received?: number,
		treatment_tags?: [],
		ups: number,
		upvote_ratio?: number,
		url: string,
		user_reports: [],
		view_count: null,
		visited: boolean,
		whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"no_ads"|"promo_all"|"some_ads"|null,
		wls: number|null,
	}[],
	discussion_type?: null|"CHAT",
	distinguished: null|"moderator"|"admin",
	domain: string,
	domain_override?: string|null,
	edited: boolean|number,
	embed_type?: null|"scrape"|"iframe",
	embed_url?: null|string,
	event_end?: number,
	event_is_live?: boolean,
	event_start?: number,
	events?: [],
	eventsOnRender?: [],
	gilded: number,
	gildings: {
		gid_1?: number,
		gid_2?: number,
		gid_3?: number,
	},
	hidden: boolean,
	href_url?: string,
	id: string,
	is_blank?: boolean,
	is_crosspostable: boolean,
	is_meta: boolean,
	is_original_content: boolean,
	is_reddit_media_domain: boolean,
	is_robot_indexable: boolean,
	is_self: boolean,
	is_video: boolean,
	link_flair_background_color: string,
	link_flair_css_class: null|string,
	link_flair_richtext: {
		a?: string,
		e: "text"|"emoji",
		t?: string,
		u?: string,
	}[],
	link_flair_template_id?: string|null,
	link_flair_text: null|string,
	link_flair_text_color: "dark"|"light",
	link_flair_type: "text"|"richtext",
	locked: boolean,
	media: null|{
		event_id?: string,
		height?: null,
		oembed?: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			height?: number|null,
			html?: string,
			marginheight?: number,
			marginwidth?: number,
			mean_alpha?: number,
			provider_name?: string,
			provider_url?: string,
			thumbnail_height?: number,
			thumbnail_url?: string,
			thumbnail_width?: number,
			title?: string,
			type?: "video"|"rich",
			url?: string,
			version?: "1.0",
			width?: number,
		},
		reddit_video?: {
			dash_url: string,
			duration: number,
			fallback_url: string,
			height: number,
			hls_url: string,
			is_gif: boolean,
			scrubber_media_url: string,
			transcoding_status: "completed",
			width: number,
		},
		type?: string,
		width?: number,
	},
	media_embed: {
		content?: string|null,
		height?: number,
		scrolling?: boolean,
		width?: number,
	},
	media_metadata?: {
		[key: string]: {
			dashUrl?: string,
			e?: "Image"|"RedditVideo"|"AnimatedImage",
			hlsUrl?: string,
			id?: string,
			isGif?: boolean,
			m?: "image/jpg"|"image/png"|"image/gif",
			p?: {
				u: string,
				x: number,
				y: number,
			}[],
			s?: {
				gif?: string,
				mp4?: string,
				u?: string,
				x: number,
				y: number,
			},
			status: "valid"|"failed"|"unprocessed",
			x?: number,
			y?: number,
		},
	}|null,
	media_only: boolean,
	mobile_ad_url?: string,
	no_follow: boolean,
	num_comments: number,
	num_crossposts: number,
	original_link?: null,
	outbound_link?: {
		created?: number|null,
		expiration?: number|null,
		url?: string,
	},
	over_18: boolean,
	parent_whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"no_ads"|"promo_all"|"some_ads"|null,
	permalink: string,
	pinned: boolean,
	poll_data?: null,
	post_hint?: "image"|"link"|"rich:video"|"self"|"hosted:video"|"video",
	preview?: {
		enabled: boolean,
		images: {
			id: string,
			resolutions: {
				height: number,
				url: string,
				width: number,
			}[],
			source: {
				height: number,
				url: string,
				width: number,
			},
			variants: {
				gif?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				mp4?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				nsfw?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
				obfuscated?: {
					resolutions: {
						height: number,
						url: string,
						width: number,
					}[],
					source: {
						height: number,
						url: string,
						width: number,
					},
				},
			},
		}[],
		reddit_video_preview?: {
			dash_url: string,
			duration: number,
			fallback_url: string,
			height: number,
			hls_url: string,
			is_gif: boolean,
			scrubber_media_url: string,
			transcoding_status: "completed",
			width: number,
		},
	},
	priority_id?: null,
	promoted?: boolean,
	promoted_by?: null,
	promoted_display_name?: null,
	promoted_url?: null,
	pwls: number|null,
	quarantine: boolean,
	removal_reason: null|"legal",
	removed_by?: null,
	removed_by_category?: null|"deleted"|"reddit"|"moderator"|"author"|"copyright_takedown"|"anti_evil_ops"|"content_takedown"|"automod_filtered"|"community_ops",
	retrieved_on: number,
	rpan_video?: {
		hls_url: string,
		scrubber_media_url: string,
	},
	score: number,
	secure_media: null|{
		event_id?: string,
		height?: null,
		oembed?: {
			author_name?: string,
			author_url?: string,
			cache_age?: number,
			description?: string,
			height?: number|null,
			html?: string,
			marginheight?: number,
			marginwidth?: number,
			mean_alpha?: number,
			provider_name?: string,
			provider_url?: string,
			thumbnail_height?: number,
			thumbnail_url?: string,
			thumbnail_width?: number,
			title?: string,
			type?: "video"|"rich",
			url?: string,
			version?: "1.0",
			width?: number,
		},
		reddit_video?: {
			dash_url: string,
			duration: number,
			fallback_url: string,
			height: number,
			hls_url: string,
			is_gif: boolean,
			scrubber_media_url: string,
			transcoding_status: "completed",
			width: number,
		},
		type?: string,
		width?: number,
	},
	secure_media_embed: {
		content?: string|null,
		height?: number,
		media_domain_url?: string,
		scrolling?: boolean,
		width?: number,
	},
	selftext: string,
	send_replies: boolean,
	show_media?: boolean,
	spoiler: boolean,
	steward_reports?: [],
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	subreddit_name_prefixed: string,
	subreddit_subscribers: number,
	subreddit_type: "public"|"user"|"restricted"|"gold_restricted"|"private"|"archived",
	suggested_sort: null|"qa"|"confidence"|"top"|"new"|"old"|"controversial"|"random"|"live",
	third_party_trackers?: null|string[],
	third_party_tracking?: null,
	third_party_tracking_2?: null,
	thumbnail: string,
	thumbnail_height?: number|null,
	thumbnail_width?: number|null,
	title: string,
	total_awards_received?: number,
	treatment_tags?: [],
	upvote_ratio?: number,
	url: string,
	whitelist_status: "all_ads"|"promo_adult_nsfw"|"house_only"|"no_ads"|"promo_all"|"some_ads"|null,
	wls: number|null,
}
