interface RedditComment_2007 {
	archived?: boolean,
	author: string,
	author_flair_css_class: null|string,
	author_flair_text: null|string,
	body: string,
	controversiality: number,
	created_utc: number|string,
	distinguished: null,
	downs?: number,
	edited: boolean|number,
	gilded: number,
	id: string,
	link_id: string,
	name?: string,
	parent_id: string,
	retrieved_on: number,
	score: number,
	score_hidden?: boolean,
	stickied?: boolean,
	subreddit: string,
	subreddit_id: string,
	ups: number,
}
