interface RedditComment_2017 {
	approved_at_utc?: null,
	author: string,
	author_cakeday?: boolean,
	author_flair_css_class: null|string,
	author_flair_text: null|string,
	banned_at_utc?: null,
	body: string,
	can_gild?: boolean,
	can_mod_post?: boolean,
	collapsed?: boolean,
	collapsed_reason?: null|"comment score below threshold"|"may be sensitive content",
	controversiality: number,
	created_utc: number,
	distinguished: null|"moderator"|"admin"|"special",
	edited: boolean|number,
	gilded: number,
	id: string,
	is_submitter?: boolean,
	link_id: string,
	mod_note?: null,
	mod_reason_by?: null,
	mod_reason_title?: null,
	parent_id: string,
	permalink?: string,
	permalink_url?: string,
	retrieved_on: number,
	score: number|null,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	subreddit_type?: "public"|"restricted"|"user",
}
