interface RedditComment {
	author: string,
	author_flair_css_class: null,
	author_flair_text: null,
	body: string,
	controversiality: number,
	created_utc: number,
	distinguished: null,
	edited: boolean,
	gilded: number,
	id: string,
	link_id: string,
	parent_id: string,
	retrieved_on: number,
	score: number,
	stickied: boolean,
	subreddit: "reddit.com"|"nsfw",
	subreddit_id: "t5_6"|"t5_vf2",
	ups: number,
}