interface RedditComment {
	author: string,
	author_flair_css_class: null,
	author_flair_text: null,
	body: string,
	controversiality: number,
	created_utc: number,
	distinguished: null,
	edited: boolean|number,
	gilded: number,
	id: string,
	link_id: string,
	parent_id: string,
	retrieved_on: number,
	score: number,
	stickied: boolean,
	subreddit: "reddit.com"|"programming"|"features"|"joel"|"ja"|"request"|"ru"|"nsfw"|"de"|"tr"|"no"|"pl"|"es"|"fr"|"it",
	subreddit_id: "t5_6"|"t5_2fwo"|"t5_21n6"|"t5_3b8o"|"t5_22i6"|"t5_21nj"|"t5_247i"|"t5_vf2"|"t5_22i0"|"t5_2478"|"t5_247e"|"t5_2475"|"t5_22i2"|"t5_22i1"|"t5_247c",
	ups: number,
}