interface RedditComment {
	_meta?: {
		is_edited?: boolean,
		note?: "no_2nd_retrieval"|"initially_unavailable",
		removal_type?: "deleted"|"removed",
		retrieved_2nd_on?: number,
		was_deleted_later?: boolean,
		was_initially_deleted?: boolean,
	},
	all_awardings?: {
		award_sub_type?: "GLOBAL"|"MODERATOR"|"COMMUNITY"|"APPRECIATION"|"PREMIUM"|"GROUP"|"CHAT_REACTION",
		award_type: "global"|"community"|"moderator",
		awardings_required_to_grant_benefits?: null|number,
		coin_price: number,
		coin_reward: number,
		count: number,
		days_of_drip_extension: number|null,
		days_of_premium: number|null,
		description: "Silver Award"|"Gold Award"|"Platinum Award"|null,
		end_date?: null|number,
		giver_coin_reward?: null|number,
		icon_format?: null|"PNG"|"APNG"|"JPG",
		icon_height: number,
		icon_url: string,
		icon_width: number,
		id: "gid_1"|"gid_2"|"gid_3",
		is_enabled: boolean,
		is_new?: boolean,
		name: "Silver"|"Gold"|"Platinum"|"Lemon Cake"|"Iron Coin"|"Apt Analysis"|"Greenseer"|"Hand of the Queen"|"Crying MJ"|"Crown"|"Hodor"|"Perfect Murder"|"Most Valuable"|"Quality OC"|"Tinfoil"|null,
		penny_donate?: null|number,
		penny_price?: null|number,
		resized_icons: {
			height: number,
			url: string,
			width: number,
		}[],
		resized_static_icons?: {
			height: number,
			url: string,
			width: number,
		}[],
		start_date?: null|number,
		static_icon_height?: number,
		static_icon_url?: string,
		static_icon_width?: number,
		sticky_duration_seconds?: null,
		subreddit_coin_reward?: number,
		subreddit_id: null|string,
		tiers_by_required_awardings?: null|{
			[key: string]: {
				awardings_required: number,
				icon: {
					format: "PNG"|"APNG",
					height: number,
					url: string,
					width: number,
				},
				resized_icons: {
					height: number,
					url: string,
					width: number,
				}[],
				resized_static_icons: {
					height: number,
					url: string,
					width: number,
				}[],
				static_icon: {
					format: null,
					height: number,
					url: string,
					width: number,
				},
			},
		},
	}[],
	approved_at_utc?: null,
	approved_by?: null,
	archived?: boolean,
	associated_award?: null|{
		award_sub_type: "GLOBAL"|"COMMUNITY"|"APPRECIATION"|"PREMIUM"|"MODERATOR"|"GROUP",
		award_type: "global"|"community"|"moderator",
		awardings_required_to_grant_benefits?: null|number,
		coin_price: number,
		coin_reward: number|null,
		count?: number,
		days_of_drip_extension: number|null,
		days_of_premium: number|null,
		description: string,
		end_date: null,
		giver_coin_reward?: null|number,
		icon_format?: null|"PNG"|"APNG",
		icon_height: number,
		icon_url: string,
		icon_width: number,
		id: "gid_1"|"gid_2"|"gid_3",
		is_enabled: boolean,
		is_new: boolean,
		name: string,
		penny_donate?: null|number,
		penny_price?: null|number,
		resized_icons: {
			height: number,
			url: string,
			width: number,
		}[],
		resized_static_icons?: {
			height: number,
			url: string,
			width: number,
		}[],
		start_date: null|number,
		static_icon_height?: number,
		static_icon_url?: string,
		static_icon_width?: number,
		sticky_duration_seconds?: null,
		subreddit_coin_reward: number,
		subreddit_id: null|string,
		tiers_by_required_awardings?: null|{
			[key: string]: {
				awardings_required: number,
				icon: {
					format: "PNG"|"APNG",
					height: number,
					url: string,
					width: number,
				},
				resized_icons: {
					height: number,
					url: string,
					width: number,
				}[],
				resized_static_icons: {
					height: number,
					url: string,
					width: number,
				}[],
				static_icon: {
					format: null,
					height: number,
					url: string,
					width: number,
				},
			},
		},
	},
	author: string,
	author_cakeday?: boolean,
	author_created_utc?: number|null,
	author_flair_background_color?: null|string,
	author_flair_css_class: null|string,
	author_flair_richtext?: {
		a?: string,
		e: "text"|"emoji",
		t?: string,
		u?: string,
	}[],
	author_flair_template_id?: null|string,
	author_flair_text: null|"PhD | Computer Science"|"BS | Physics"|"PhD | Robotics"|"Canada"|"MD | OB/GYN | GYN Oncology"|"Professor | Computer Science"|"Nürnberg"|"BS|Chemical Engineering"|"BS | Physics and Astronomy|Education"|"Professor|Computing|Machine Learning"|"BS | Zoology | Ecology and Entomology"|"PhD | Synthetic Organic Chemistry",
	author_flair_text_color?: null|"dark"|"light"|"",
	author_flair_type?: "text"|"richtext",
	author_fullname?: string|null,
	author_is_blocked?: boolean,
	author_patreon_flair?: boolean,
	author_premium?: boolean,
	awarders?: ("Bioniclegenius"|"Belli91"|"shuntzu7"|"wearewildwinter"|"ucbsuperfreak"|"Dragonster82"|"NovaKevin"|"Dev_h1pp0p0t4mu5"|"ForgottenLoreInAutum")[],
	banned_at_utc?: null,
	banned_by?: null,
	body: string,
	body_html?: string|null,
	can_gild?: boolean,
	can_mod_post?: boolean,
	collapsed?: boolean,
	collapsed_because_crowd_control?: null,
	collapsed_reason?: null|"comment score below threshold"|"potentially toxic"|"may be sensitive content"|"potentially toxic content",
	collapsed_reason_code?: null|"DELETED"|"LOW_SCORE"|"POTENTIALLY_TOXIC",
	comment_type?: null|"PREDICTION",
	controversiality: number,
	created?: number|null,
	created_utc: number|string,
	distinguished: null|"moderator"|"admin"|"special",
	downs?: number,
	editable?: boolean,
	edited: number|boolean,
	expression_asset_data?: {
		[key: string]: {
			avatar: {
				e: "Image",
				m: "image/png",
				s: {
					u: string,
					x: number,
					y: number,
				},
			},
			expression: {
				e: " Image",
				l: "FRONT"|"BACK",
				m: "image/png",
				n: "cry"|"bravo"|"fire"|"starstruck"|"heart"|"clown"|"take_my_energy"|"holo_card"|"winner"|"nani"|"laugh"|"webman"|"dizziness"|"spooky"|"cameras",
				s: {
					u: string,
					x: number,
					y: number,
				},
			}[],
			perspective: "CROPPED"|"FULL_BODY",
			position: "CENTER"|"LEFT",
			size: "SIZE_1_X_1"|"SIZE_1_X_2",
		},
	},
	gilded: number,
	gildings?: {
		gid_1?: number,
		gid_2?: number,
		gid_3?: number,
	},
	id: string,
	is_submitter?: boolean,
	likes?: null|boolean,
	link_id: string,
	locked?: boolean,
	media_metadata?: {
		[key: string]: {
			e?: "AnimatedImage"|"Image",
			ext?: string,
			id?: "emote|emo_pack_1|dance"|"emote|emo_pack_1|clappy"|"emote|emo_pack_1|dab"|"emote|emo_pack_1|respect"|"emote|emo_pack_1|uNfOrTuNaTeLy"|"emote|emo_pack_1|confused"|"emote|emo_pack_1|bush"|"emote|emo_pack_1|cuddle"|"emote|emo_pack_1|oof"|"emote|emo_pack_1|wow"|"emote|emo_pack_1|chug"|"emote|emo_pack_1|default"|"emote|emo_pack_1|blink"|"emote|free_emotes_pack|facepalm"|"emote|emo_pack_1|soon",
			m?: "image/gif"|"image/png"|"image/jpeg",
			p?: {
				u: string,
				x: number,
				y: number,
			}[],
			s?: {
				gif?: string,
				mp4?: string,
				u?: string,
				x: number,
				y: number,
			},
			status: "valid"|"unprocessed"|"invalid",
			t?: "sticker"|"emoji"|"giphy",
		},
	},
	mod_note?: null,
	mod_reason_by?: null,
	mod_reason_title?: null,
	mod_reports?: []|null,
	name?: string,
	no_follow?: boolean,
	num_reports?: null,
	parent_id: string,
	permalink?: string,
	permalink_url?: string,
	quarantined?: boolean,
	removal_reason?: null|"legal",
	replies?: ""|null,
	report_reasons?: null,
	retrieved_on?: number|null,
	retrieved_utc?: number,
	rte_mode?: "markdown"|"richtext",
	saved?: boolean|null,
	score: number|null,
	score_hidden?: boolean,
	send_replies?: boolean,
	steward_reports?: [],
	stickied?: boolean,
	subreddit: "reddit.com"|"nsfw"|"programming"|"features"|"joel"|"ja"|"request"|"ru"|"de"|"tr"|"no"|"pl"|"es"|"fr"|"it",
	subreddit_id: "t5_6"|"t5_vf2"|"t5_2fwo"|"t5_21n6"|"t5_3b8o"|"t5_22i6"|"t5_21nj"|"t5_247i"|"t5_22i0"|"t5_2478"|"t5_247e"|"t5_2475"|"t5_22i2"|"t5_22i1"|"t5_247c",
	subreddit_name_prefixed?: string,
	subreddit_type?: "public"|"restricted"|"user"|"archived"|"private"|"gold_restricted",
	top_awarded_type?: null,
	total_awards_received?: number,
	treatment_tags?: ("econ:render:lottie:redstar"|"econ:render:lottie:bulb"|"econ:render:lottie:sunny2"|"econ:render:lottie:cutie"|"econ:render:glow:ff0000"|"econ:render:bubble:flame"|"econ:render:lottie:heartbeat"|"econ:render:lottie:champagne"|"econ:render:lottie:sunny"|"econ:render:lottie:halloween2020"|"econ:render:lottie:santasnoo")[],
	unrepliable_reason?: null|"NEAR_BLOCKER",
	ups?: number,
	user_reports?: []|null,
}
