interface RedditComment {
	author: string,
	author_flair_css_class: null|"physics"|"NUERN"|"compsci"|"  reward1"|"bio"|"chem"|"med reward1"|"   reward2",
	author_flair_text: null|string,
	body: string,
	controversiality: number,
	created_utc: number,
	distinguished: null,
	edited: boolean|number,
	gilded: number,
	id: string,
	link_id: string,
	parent_id: string,
	retrieved_on: number,
	score: number,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	ups: number,
}