interface RedditComment {
	author: string,
	author_flair_css_class: null|"physics"|"compsci"|"eng"|"NUERN"|"bio"|"chem",
	author_flair_text: null|"BS | Physics"|"Professor | Computer Science"|"Nürnberg"|"BS|Chemical Engineering"|"BS | Physics and Astronomy|Education"|"Professor|Computing|Machine Learning"|"PhD | Computer Science"|"BS | Zoology | Ecology and Entomology"|"PhD | Robotics"|"PhD | Synthetic Organic Chemistry",
	body: string,
	controversiality: number,
	created_utc: number,
	distinguished: null,
	edited: boolean|number,
	gilded: number,
	id: string,
	link_id: string,
	parent_id: string,
	retrieved_on: number,
	score: number,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	ups: number,
}