interface RedditComment {
	author: string,
	author_flair_css_class: null|"physics"|"eng"|"compsci"|"med",
	author_flair_text: null|"BS | Physics"|"PhD | Robotics"|"PhD | Computer Science"|"MD | OB/GYN | GYN Oncology",
	body: string,
	controversiality: number,
	created_utc: number,
	distinguished: null,
	edited: boolean|number,
	gilded: number,
	id: string,
	link_id: string,
	parent_id: string,
	retrieved_on: number,
	score: number,
	stickied: boolean,
	subreddit: string,
	subreddit_id: string,
	ups: number,
}